services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      db_root_password: password  
      db_name: movies 
      MYSQL_SERVICE_HOST: db  
      MYSQL_SERVICE_PORT: 3306 
    depends_on:
      - db
    networks:
      - moviesapp-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: movies 
    ports:
      - "3306:3306" 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - moviesapp-network

networks:
  moviesapp-network:
    driver: bridge
